name: build

on:
  pull_request:
  push:
    branches:
      - build

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            crypto: openssl
            opts: "--disable-debug"
            cc: gcc
            cflags: "-O2 -Wall"
          - os: ubuntu-latest
            crypto: openssl
            opts: "--enable-debug"
            cc: clang
            cflags: "-O2"
          - os: ubuntu-latest
            crypto: libgcrypt
            opts: "--enable-debug"
            cc: gcc
            cflags: "-O2"
          - os: ubuntu-latest
            crypto: libgcrypt
            opts: "--disable-debug"
            cc: clang
            cflags: "-O2 -Wall"
          - os: ubuntu-26.04-arm
            crypto: openssl
            opts: "--enable-debug"
            cc: gcc
            cflags: "-O2"
          - os: ubuntu-26.04-arm
            crypto: openssl
            opts: "--disable-debug"
            cc: clang
            cflags: "-O2 -Wall"
          - os: ubuntu-26.04-arm
            crypto: libgcrypt
            opts: "--disable-debug"
            cc: gcc
            cflags: "-O2 -Wall"
          - os: ubuntu-26.04-arm
            crypto: libgcrypt
            opts: "--enable-debug"
            cc: clang
            cflags: "-O2"
          - os: macos-latest
            crypto: openssl
            opts: "--disable-debug"
            cflags: "-O2 -Wall"
            cc: clang
          - os: macos-latest
            crypto: openssl
            opts: "--enable-debug"
            cc: clang
            cflags: "-O2"
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Get OS version
        run: |
          if expr "${{ matrix.os }}" : "ubuntu" >/dev/null; then
            cat /etc/os-release
          elif expr "${{ matrix.os }}" : "macos" >/dev/null; then
            sw_vers
          fi
      - name: Get uname
        run: uname -a
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install deps
        run: |
          if expr "${{ matrix.os }}" : "ubuntu" >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y autoconf automake libtool \
              libgcrypt20-dev libssl-dev zlib1g-dev libbz2-dev faketime
          elif expr "${{ matrix.os }}" : "macos" >/dev/null; then
            brew install autoconf automake libtool
          fi
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          ./configure \
            --with-crypto-lib="${{ matrix.crypto }}" ${{ matrix.opts }} \
            CC="${{ matrix.cc }}" CFLAGS="${{ matrix.cflags }}"
      - name: Get config.log
        run: cat config.log
      - name: Get config.h
        run: cat config.h
      - name: Build
        run: make V=1 CFLAGS="${{ matrix.cflags }} -Werror"
      - name: Test
        run: |
          expr "${{ matrix.os }}" : "macos" >/dev/null && tmp="/private/tmp"
          make check chain_lint=t verbose=t VERBOSE=t \
            TMPDIR="${tmp:-/tmp}" root="${tmp:-/tmp}/munge-test-$$"
      - name: Get test-suite.log
        if: ${{ failure() }}
        run: find . -type f -name "test-suite.log" -execdir cat {} \;
